version: '3.9'
services:
  parastas:
    build:
      context: .
      dockerfile: Dockerfile.arm
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
