version: '3.9'
services:
  parastas:
    environment:
    - PARASTAS_USERNAME=${PARASTAS_USERNAME}
    - PARASTAS_PASSWORD=${PARASTAS_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile.arm
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
